### ISSUE TITLE
$route is undefined

### ISSUE THREAD

**Issue by lichenglu** [eddyerburgh/stub-route-in-vue-unit-tests#1]
Hi! Thanks for this great tutorial! And great work for the Avoriaz 👍 

## What is the issue?

I had a problem by following your example that said `$route is undefined`. I am wondering if you know what might be the problem?

Here are the error messages:
In terminal, `undefined is not an object (evaluating 'this.$route.params')`
In browser (I am using PhantomJS with Karma), ` Cannot read property 'params' of undefined`

## What do I have?
Here is the `component` code:

```
<template>
  <iframe :src="iFrameUrl" class="lo-module"></iframe>
</template>

<script>
import { mapActions } from 'vuex'

export default {
  name: 'module-iframe',
  data: function () {
    return {
      iFrameUrl: this.$route.params.url
    }
  },
  created: function () {
    if (this.$route.params.id) { this.setInProgress(this.$route.params) }
  },
  methods: {
    ...mapActions({
      setInProgress: 'modules/setInProgress'
    })
  }
}
</script>
```

And here is the test:

```
  it('should call setInProgress if $route.params.id is NOT null', () => {
    const instance = Vue.extend()
    const $route = {
      params: {
        id: 'test id',
        url: 'test url'
      }
    }
    const wrapper = mount(ModuleContent, {
      globals: { $route },
      instance
    })
    expect(wrapper.vm.$route).to.deep.equal($route)
    // assert(actions.setInProgress.calledOnce)
  })
```
## What did I do?
1. I commented out codes in the `created` lifecycle hook of the `component`
2. I tried to change `created` to `mounted`
But the issue still exists, since `$route` is not injected, and `this.$route` is undefined

**Comment by eddyerburgh** [comment]
Are you calling `vue.use (VueRouter)` somewhere in your tests?

**Comment by eddyerburgh** [comment]
This could  be caused by the vue webpack template rewriting vue router files before running tests - see https://github.com/eddyerburgh/avoriaz/issues/80

**Comment by lichenglu** [comment]
Hi Eddy, thanks for the prompt reply!
Ahh, I am indeed calling `Vue.ues(Router)` in my test index file. I will remove it and let you know the results! Thank you!

**Comment by lichenglu** [comment]
Hi @eddyerburgh, I am still having problems injecting $route. In my test index file, `Vue.ues(Router)` is not called, but it is used in some of the test files, does it matter? (I guess I do not understand what `Vue.use(router)` does behind the scene). 
I am having the error `setting a property that has only a getter` when using the enlightened way you showed:
```
    const scopedVue = Vue.extend()
    const $route = {
      name: 'test name - enlightened',
      params: {
        id: 'test id',
        url: 'test url'
      }
    }
    scopedVue.prototype.$route = $route

    const Constructor = scopedVue.extend(ModuleContent)
    const vm = new Constructor().$mount()
    expect(vm.$route).to.deep.equal($route)
```

**Comment by eddyerburgh** [comment]
Yeah you can't call Vue.use(router) and then overwrite `$route` or `$router`

Vue.use(router) adds $route and $router as immutable properties to the base Vue instance.

If you install Vue.router on a scopedVue, and then pass scopedVue as instance to mount the tests should work:

```js
import { cloneDeep } from 'lodash'
import Vue from 'vue'
import VueRouter from 'vue-router'

const scopedInstance = Vue.extend()
scopedInstance.version = Vue.version
scopedInstance.config = cloneDeep(Vue.config)
scopedInstance.util = cloneDeep(Vue.util)

 instance.use(VueRouter)

const wrapper = mount(ComponentThatRequiresVueRouter, {
  instance: scopedInstance
})
```

**Comment by lichenglu** [comment]
Thanks for the explanation. But now I have this error `undefined is not a constructor (evaluating 'Vue.set(parentState, moduleName, module.state)')` when trying to implement a scopedInstance. It seems to be an error of using `vuex`, do I need to do anything in order to use vuex for the scopedInstance? Thank you so much!

```
const scopedInstance = Vue.extend()
scopedInstance.version = Vue.version
scopedInstance.config = cloneDeep(Vue.config)
scopedInstance.util = cloneDeep(Vue.util)
scopedInstance.use(VueRouter)
scopedInstance.use(Vuex)
```

**Comment by eddyerburgh** [comment]
Ah there's a problem using Vuex more than once in one test suite ☹️

I haven't got a solution to this unfortunately

**Comment by lichenglu** [comment]
I see, thank you! And I am looking forward to the official testing library you are involved with!

**Comment by DarwinniwraD** [comment]
@lichenglu, have you got an alter way to go through the ```$route is undefined``` ? thank you!

**Comment by steven87vt** [comment]
Just FYI anyone else stumble across this the docs have a pretty simple example that works well: [Mounting#LocalVue](https://vue-test-utils.vuejs.org/api/options.html#localvue)
